URDF files for the Chess pieces
abhidxt299/RoManOV_Simulation pull request #8
Opened 2020-07-19 11:09 UTC by Abhay2526

2020-07-19 11:20 UTC, veds12 commented
You exported these files from stl files right?

2020-07-19 11:30 UTC, adbidwai commented
Add an image of en example piece in Gazebo simulator too in .png/.jpeg format

2020-07-19 14:33 UTC, abhidxt299 requested changes
The designs are really good.

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/Bishop_Black/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/Castle_black/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here.

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/Queen_black/manifest.xml
> +  <maintainer email="TODO@email.com" />
Same here. Do add your email.

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/Rook_black/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/king_black/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/Black/pawn_black/manifest.xml
> +  <license>BSD</license>
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/Bishop_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/Castle_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/Queen_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/Rook_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/king_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 14:33 UTC, abhidxt299 commented on URDF_Chess_pieces/White/pawn_white/manifest.xml
> +  <maintainer email="TODO@email.com" />
You can add your email here

2020-07-19 17:03 UTC, Abhay2526 commented
> You exported these files from stl files right?

There was a direct converter to convert the Solidworks file to URDF

2020-07-20 06:26 UTC, abhidxt299 approved these changes
Good job.

2020-07-20 06:44 UTC, veds12 approved these changes
We can merge this PR for now

2020-07-20 06:45 UTC, merged